### ISSUE TITLE
[Feature Request] Don't prevent applications from starting up if credentials cannot be fetched

### ISSUE THREAD

**Issue by lucasavila00** [Nickforall/ExFirebaseAuth#18]
First of all, thanks @Nickforall for the awesome library.
I found the source code really amazing, an awesome source of good elixir :)

I would like to request changes to the behavior of the library, so that it no longer prevents app initialization if it couldn't fetch the credentials. Somewhere along [these lines ](https://github.com/Nickforall/ExFirebaseAuth/blob/main/lib/key_store.ex#L16) should retry or ignore such errors.

In my current project I use firebase auth for a minor feature, so if it fails, I would like everything else to continue to work.

Also, I use this library behind a layer of custom code, and at test time I don't actually test against this library. If I turn my internet off then my tests won't run anymore.

**Comment by Nickforall** [comment]
Haha thanks for the kind words, and great feedback, will have a look shortly
