### ISSUE TITLE
Error when verifying tokens ("Public key retrieved from google was not found or could not be parsed") 

### ISSUE THREAD

**Issue by akashvibhute** [Nickforall/ExFirebaseAuth#52]
Getting the same error consistently for last 30 minutes. First time using this library.
 
Version - `{:ex_firebase_auth, "~> 0.5.1"}`

ets table contains only one entry with following value -

```elixir
iex(1)> :ets.first(ExFirebaseAuth.KeyStore)
"6a4f87ff5d93fa6ea03e5c6e88eea0acd2a232a9"
iex(2)> :ets.last(ExFirebaseAuth.KeyStore)
"6a4f87ff5d93fa6ea03e5c6e88eea0acd2a232a9"
iex(3)> :ets.lookup(ExFirebaseAuth.KeyStore, "6a4f87ff5d93fa6ea03e5c6e88eea0acd2a232a9")
[
  {"6a4f87ff5d93fa6ea03e5c6e88eea0acd2a232a9",
   %JOSE.JWK{
     fields: %{},
     keys: :undefined,
     kty: {:jose_jwk_kty_rsa,
      {:RSAPublicKey,
       26683466267166000117937282941287368499188964267704350320016815060755186299190334552341359030182847862883650390995706932990206917504303874597159717626156857776530120286608824298039026662712309062585296391513994028930201376912224740158628136408547035523323040966599847393117788904610391693639428199426775371439187431710883575502972086796633627213970033547315970319396410708150818633921757026450722384908347116277890243025314192440036812929920627983552722832658264926504359043778585873454116991087894748041249472749584754467425019137143154494316545575161017698890108258608397227982398909111303817013085192016995952648177,
       65537}}
   }}
]
```

Verify token returns 
```elixir
{:error, "Public key retrieved from google was not found or could not be parsed"}
```

_Originally posted by @akashvibhute in https://github.com/Nickforall/ExFirebaseAuth/issues/13#issuecomment-1086871500_

**Comment by jsmestad** [comment]
@akashvibhute Are you validating an `idToken` or a session cookie? They are signed by two different sets of keys and this library only supports checking firebase `idToken` signatures and not session cookies.

I am going to try and make a PR to add checking for the latter

**Comment by akashvibhute** [comment]
@jsmestad It might have been the idToken from session cookie. Anyway I stopped using session cookie on my frontend and switched to joken/jwks for the validation on backend after the errors.
